spring:
  application:
    name: routory-backend

app:
  jwtSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey

cookie:
  domain: localhost

logging:
  config: classpath:log4j2.yaml